import { Dimensions } from 'react-native';

export default {
  deviceHeight: Dimensions.get('window').height,
  deviceWidth: Dimensions.get('window').width,
  heightTiny: 12,
  heightSmall: 16,
  heightNormal: 20,
  heightMedium: 30,
  heightLarge: 40,
  heightLargest: 45,
  standardGapTiny: 10,
  standardGapTiniest: 5,
  standardGapSmall: 12,
  standardGapMedium: 15,
  standardGapLarge: 20,
  standardGapBig: 24,
  fontSizeTiny: 14,
  fontSizeSmall: 16,
  fontSizeRegular: 18,
  fontSizeNormal: 20,
  fontSizeMedium: 24,
  fontSizeBig: 26,
  fontSizeLarge: 30,
  fontSizeLargest: 36,
};
